src/ZE/BABundle/Entity/Address.php
<?php

namespace ZE\BABundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Gedmo\Mapping\Annotation as Gedmo;



/**
 * Address
 * @ORM\Table(name="address")
 * @ORM\Entity(repositoryClass="ZE\BABundle\Entity\Repository\Address")
 */
class Address
{

    /**
     * Hook timestampable behavior
     * updates createdAt, updatedAt fields
     */
    use TimestampableEntity;

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="address", type="string",  nullable=true)
     */
    private $address;


    /**
     * @var string
     *
     * @ORM\Column(name="latitude", type="float", precision=7, nullable=true)
     */
    private $latitude;

    /**
     * @var string
     *
     * @ORM\Column(name="longitude", type="float", precision=7, nullable=true)
     */
    private $longitude;

    /**
     * @var \City
     *
     * @ORM\ManyToOne(targetEntity="City")
     * @ORM\JoinColumn(name="city_id", referencedColumnName="id")
     */
    private $city;


    /**
     * @ORM\ManyToOne(targetEntity="Region")
     * @ORM\JoinColumn(name="region_id", referencedColumnName="id")
     */
    private $region;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }


    /**
     * Set address
     *
     * @param string $address
     *
     * @return Address
     */
    public function setAddress($address)
    {
        $this->address = $address;

        return $this;
    }

    /**
     * Get address
     *
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Set latitude
     *
     * @param string $latitude
     *
     * @return Address
     */
    public function setLatitude($latitude)
    {
        $this->latitude = $latitude;

        return $this;
    }

    /**
     * Get latitude
     *
     * @return string
     */
    public function getLatitude()
    {
        return $this->latitude;
    }

    /**
     * Set longitude
     *
     * @param string $longitude
     *
     * @return Address
     */
    public function setLongitude($longitude)
    {
        $this->longitude = $longitude;

        return $this;
    }

    /**
     * Get longitude
     *
     * @return string
     */
    public function getLongitude()
    {
        return $this->longitude;
    }

    /**
     * Set city
     *
     * @param \ZE\BABundle\Entity\City $city
     *
     * @return Address
     */
    public function setCity(\ZE\BABundle\Entity\City $city = null)
    {
        $this->city = $city;

        return $this;
    }

    /**
     * Get city
     *
     * @return \ZE\BABundle\Entity\City
     */
    public function getCity()
    {
        return $this->city;
    }

    public function __toString()
    {
        return $this->address . ' ' . $this->getCity()->getName();
    }

    public function getLongName()
    {
        $region = $this->getRegion();
        if (!empty($region)){
            $region = $this->getRegion()->getShortName() . ' ';
        }

        $name = $this->address . ' ' . $this->getCity()->getName() .' ' . $region
            . $this->getCity()->getCountry()->getName() ;
        return $name;
    }

    /** @ORM\ManyToMany(targetEntity="Association", mappedBy="addresses") **/
    protected $associations;

   

    /**
     * Set region
     *
     * @param \ZE\BABundle\Entity\Region $region
     *
     * @return Address
     */
    public function setRegion(\ZE\BABundle\Entity\Region $region = null)
    {
        $this->region = $region;

        return $this;
    }

    /**
     * Get region
     *
     * @return \ZE\BABundle\Entity\Region
     */
    public function getRegion()
    {
        return $this->region;
    }
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->associations = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add association.

     *
     * @param \ZE\BABundle\Entity\Association $association
     *
     * @return Address
     */
    public function addAssociation(\ZE\BABundle\Entity\Association $association)
    {
        $this->associations[] = $association;

        return $this;
    }

    /**
     * Remove association.

     *
     * @param \ZE\BABundle\Entity\Association $association
     */
    public function removeAssociation(\ZE\BABundle\Entity\Association $association)
    {
        $this->associations->removeElement($association);
    }

    /**
     * Get associations.

     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getAssociations()
    {
        return $this->associations;
    }
}

src/ZE/BABundle/Entity/Association.php
<?php
/**
 * Created by PhpStorm.
 * User: z
 * Date: 22/03/14
 * Time: 19:46
 */

namespace ZE\BABundle\Entity;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;


/**
    * An item a user can have a many to many relationship with, ie: Association, artist
    *
    * @ORM\Entity
    * @ORM\Table(name="association")
    * @ORM\InheritanceType("SINGLE_TABLE")
    * @ORM\DiscriminatorColumn(name="type", type="string")
    * @ORM\DiscriminatorMap({"association" = "Association", "musician" = "Musician", "band" = "Band"})
    * @ORM\Entity(repositoryClass="ZE\BABundle\Entity\Repository\Association")
    */
class Association
{

    use TimestampableEntity;
    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string",  nullable=false)
     */
    protected $name;
    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text", nullable=true)
     */
    protected $description;

    /**
     * @ORM\ManyToMany(targetEntity="Address", inversedBy="associations")
     * @ORM\JoinTable(name="association_address",
     *   joinColumns={@ORM\JoinColumn(name="association_id", referencedColumnName="id")},
     *   inverseJoinColumns={@ORM\JoinColumn(name="address_id", referencedColumnName="id")}
     * )
     */
    protected $addresses;

    /**
     * @ORM\OneToMany(targetEntity="Document", mappedBy="association", cascade={"persist"})
     */
    protected $documents;

    /**
     * @ORM\ManyToMany(targetEntity="Genre", inversedBy="associations")
     * @ORM\JoinTable(name="association_genre",
     *   joinColumns={@ORM\JoinColumn(name="association_id", referencedColumnName="id")},
     *   inverseJoinColumns={@ORM\JoinColumn(name="genre_id", referencedColumnName="id")}
     * )
     */
    protected $genres;

    /**
     * @ORM\ManyToOne(targetEntity="User", inversedBy="associations",cascade={"persist"})
     */
    protected $user;

    /**
     * @var integer $id
     *
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @Gedmo\Slug(fields={"name", "id"})
     * @ORM\Column(unique=true)
     */
    private $slug;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    public function __toString()
    {
        return $this->name;
    }


    public function __construct()
    {
        $this->documents = new ArrayCollection();
        $this->addresses = new ArrayCollection();
        $this->genres = new ArrayCollection();
    }



    /**
     * Add documents
     *
     * @param \ZE\BABundle\Entity\Document $documents
     * @return Association
     */
    public function addDocument(\ZE\BABundle\Entity\Document $documents)
    {
        $this->documents[] = $documents;

        return $this;
    }

    /**
     * Remove documents
     *
     * @param \ZE\BABundle\Entity\Document $documents
     */
    public function removeDocument(\ZE\BABundle\Entity\Document $documents)
    {
        $this->documents->removeElement($documents);
    }

    /**
     * Get addresss
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getAddresses()
    {
        return $this->addresses;
    }

    /**
     * Add addresss
     *
     * @param \ZE\BABundle\Entity\Address $addresss
     * @return Association
     */
    public function addAddress(\ZE\BABundle\Entity\Address $addresss)
    {
        $this->addresses[] = $addresss;

        return $this;
    }

    /**
     * Remove addresss
     *
     * @param \ZE\BABundle\Entity\Address $addresss
     */
    public function removeAddress(\ZE\BABundle\Entity\Address $addresss)
    {
        $this->addresses->removeElement($addresss);
    }

    /**
     * Get documents
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getDocuments()
    {
        return $this->documents;
    }
    /**
     * Add genres
     *
     * @param \ZE\BABundle\Entity\Genre $genres
     * @return Association
     */
    public function addGenre(\ZE\BABundle\Entity\Genre $genres)
    {
        $this->genres[] = $genres;

        return $this;
    }

    /**
     * Remove genres
     *
     * @param \ZE\BABundle\Entity\Genre $genres
     */
    public function removeGenre(\ZE\BABundle\Entity\Genre $genres)
    {
        $this->genres->removeElement($genres);
    }

    /**
     * Get genres
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getGenres()
    {
        return $this->genres;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Association
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return Association
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription()
    {
        return $this->description;
    }

    public function setUser(User $user)
    {
        $this->user = $user;
    }

    public function getUser()
    {
        return $this->user;
    }

    public function getType()
    {
        return get_class($this);
    }

    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * Set slug
     *
     * @param string $slug
     *
     * @return Association
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;

        return $this;
    }

    public function getDocumentsByTypeId($typeId)
    {
        $criteria = Criteria::create();
        $criteria->where(Criteria::expr()->eq('type', $typeId));

        return $this->documents->matching($criteria);
    }

    public function getClassName()
    {
        $class = explode('\\', get_class($this));
        return strtolower( array_pop($class) );

    }
}

src/ZE/BABundle/Resources/views/_associated_group.html.twig
{% block _associated_container %}
    {% if assocs is defined %}
        <div class="panel panel-default">
            <div class="panel-heading">{{ type |capitalize }}s Associated With:</div>
            <div class="panel-body">
                <div class="row assoc-wrapper-row">

                    {% for assoc in assocs %}
                        {% block assoc_loop %}
                            {% set entity_show_path= path( type ~'_show', { 'slug': assoc.band.slug }) %}
                            {% include 'ZEBABundle::_associated_row.html.twig' with {'assoc' : assoc.band} %}
                        {% endblock assoc_loop %}
                    {% endfor %}
                </div>

            </div>

        </div>
    {% endif %}

{% endblock _associated_container %}

src/ZE/BABundle/Resources/views/_associated_row.html.twig
<div class="panel ">
    <div class="col-sm-4 col-md-4">
        <div class="assoc-image">
            <a href="{{ entity_show_path }}">
                {% if assoc.documents[0] is defined %}
                    <img src="{{ assoc.documents[0].getWebPath  | imagine_filter('assoc') }}"
                         alt="">
                {% else %}
                    <img src="http://placehold.it/200x120" alt="Project Name">
                {% endif %}
            </a>
        </div>
    </div>
    <div class="col-sm-8 col-md-8 assoc-text">
        <h3>{{ assoc.name }}</h3>

        <p>
            {{ assoc.description }}
        </p>

        <p>
            {% include 'ZEBABundle::genres.html.twig' with {'entity': assoc  } %}
            {% include 'ZEBABundle::locations.html.twig' with {'entity':assoc } %}
            {% block assoc_actions %}
            {% if type == 'band' and is_granted('ROLE_USER') %}

                {% if app.user.musicians|length == 1%}
                    {% include 'ZEBABundle::request_audition_button.html.twig'
                    with {'bandId': assoc.id, 'musicianId': app.user.musicians[0].id} %}
                {% elseif app.user.musicians|length > 1%}
                    {% include 'ZEBABundle::request_audition_select_musician.html.twig'
                    with {'bandId': assoc.id,'musicians': app.user.musicians} %}
                {% endif %}


            {% endif %}
        {% endblock assoc_actions %}
        </p>
    </div>
</div>

src/ZE/BABundle/Resources/views/bands_associated.html.twig
{% extends 'ZEBABundle::_associated_group.html.twig' %}
{% block assoc_loop %}
    {% set entity_show_path= path( type ~'_show', { 'slug': assoc.slug }) %}
    {% include 'ZEBABundle::_associated_row.html.twig' with {'assoc' : assoc} %}
{% endblock assoc_loop %}

src/ZE/BABundle/Resources/views/edit_assoc.html.twig
{% extends '::base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    {{ form_stylesheet(edit_form) }}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ form_javascript(edit_form) }}
{% endblock %}
{% block container %}
    {% include 'ZEBABundle::show_new_location_modal.html.twig' %}
    <button class="btn btn-primary fa fa-globe" id="btnShowNewLocation" data-target="#largeModal"> Add New Address
    </button>
    <ul class="nav nav-pills">
        <li class="active"><a href="#tabBandsMain" data-toggle="pill">General</a></li>
        {% if edit_form.vars.value.className == 'band' %}
            <li><a href="#tabBandsVacancies" data-toggle="pill">Band Vacancies</a></li>
        {% endif %}
        <li><a href="#tabBandsMedia" data-toggle="pill">Media</a></li>
    </ul>

    {{ form_start(edit_form) }}
    <div class="tab-content" id="tab-content">
        <div class="tab-pane " id="tabBandsMedia">
            <div class="row">
                {% for document in edit_form.documents.vars.data %}
                    <div class="col-xs-6 col-sm-4 col-md-3 col-lg-3" name="chkDocuments"
                         id="divDocument{{ document.id }}"><input type="checkbox" id="{{ document.id }}"/><img
                                src="{{ document.getWebPath  | imagine_filter('assoc') }}"></div>
                {% endfor %}
            </div>
            <div class="row" id="mediaControls">
                <a href="#" class="btn btn-danger fa fa-trash-o" id="deleteDocument"> Delete Document</a>
            </div>

        </div>
        <div class="tab-pane active" id="tabBandsMain">
            <h4>Band Details</h4>
            {{ form_row(edit_form.name) }}
            {{ form_row(edit_form.description) }}
            {{ form_row(edit_form.genres) }}
            {% if edit_form.vars.value.className == 'band' %}
                {{ form_row(edit_form.musicians) }}
            {% else %}
                {{ form_row(edit_form.instruments) }}
                {{ form_row(edit_form.bands) }}
            {% endif %}
            {{ form_row(edit_form.addresses) }}
        </div>
        {% if edit_form.vars.value.className == 'band' %}
            <div class="tab-pane " id="tabBandsVacancies">

                <div id="panelBandVacancies" class="panel"
                     data-prototype="{{ form_widget(edit_form.bandVacancyAssociations.vars.prototype)|e }}">
                    <h4>Band Vacancies</h4>
                    {% for bandVacancyAssociation in edit_form.bandVacancyAssociations %}
                        <div class="panel-group">
                            <div class="panel panel-default" id="panel{{ bandVacancyAssociation.vars.data.id }}">
                                <div class="panel-heading">
                                    <h4 class="panel-title">
                                        <a data-toggle="collapse"
                                           data-target="#collapse{{ bandVacancyAssociation.vars.data.id }}"
                                           href="#collapse{{ bandVacancyAssociation.vars.data.id }}">
                                            {{ bandVacancyAssociation.vars.data.bandVacancy.name }}
                                        </a>
                                    </h4>
                                </div>
                                <div data-id="{{ bandVacancyAssociation.vars.data.id }}"
                                     id="collapse{{ bandVacancyAssociation.vars.data.id }}"
                                     class="panel-collapse collapse in">
                                    <div class="panel-body" id="panel-body{{ bandVacancyAssociation.vars.data.id }}">
                                        <div>
                                            {{ form_row(bandVacancyAssociation.bandVacancy.name) }}

                                            {{ form_row(bandVacancyAssociation.bandVacancy.comment) }}
                                            {% for genre in bandVacancyAssociation.bandVacancy.genres %}
                                                {{ form_row(genre) }}
                                            {% endfor %}
                                            {% for instrument in bandVacancyAssociation.bandVacancy.instruments %}
                                                {{ form_row(instrument) }}
                                            {% endfor %}

                                        </div>
                                    </div>
                                    <button class="btn btn-danger fa fa-trash-o"
                                            id="deleteBandVacancyAssociation{{ bandVacancyAssociation.vars.data.id }}">
                                        Delete
                                        Vacancy
                                    </button>
                                </div>
                            </div>

                        </div>

                    {% endfor %}

                </div>
                {% include 'ZEBABundle::show_new_band_vacancy_modal.html.twig' %}
            </div>
        {% endif %}
        {{ form_end(edit_form) }}

    </div><!-- tab content -->
    <br>
    <div id="divNewDocument">
        <form id="frm_upload_document" name="frm_upload_document" method="post" enctype="multipart/form-data"
              action="{{ path('document_create', { 'aid':  edit_form.vars.data.id }) }}">
            <input class="btn btn-primary fa fa-plus-circle " id="btnShowNewDocument" name="btnShowNewDocument"
                   type="file" title=" Add New Document"/>
        </form>
    </div>


    <script type="application/javascript">
        function addForm($collectionHolder, $elementToPrepend) {
            // Get the data-prototype explained earlier
            var prototype = $collectionHolder.data('prototype');
            // get the new index
            var index = $collectionHolder.data('index');
            // Replace '__name__' in the prototype's HTML to
            // instead be a number based on how many items we have

            var newForm = prototype.replace(/__name__/g, index);
            $("#" + $elementToPrepend).prepend(newForm);


        }

        jQuery(document).ready(function () {
            $('input[type=file]').bootstrapFileInput();
            $("#mediaControls").append($("#divNewDocument"));
            var counter = -1;
            {% if edit_form.vars.value.className == 'band' %}
                {% for bandVacancyAssociation in edit_form.bandVacancyAssociations %}
                    counter++;
                    $("#ze_babundle_band_bandVacancyAssociations_" + counter + "_bandVacancy")
                            .appendTo($('#panel-body{{ bandVacancyAssociation.vars.data.id }}'));
                {% endfor %}
            {% endif %}
            var bandVacanciesHolder;
            var addNewBandVacancy = $('<button href="#modalShowNewBandVacancy" data-toggle="modal"  class="btn btn-primary fa fa-plus-circle" id="btnShowNewBandVacancy" > Add New Vacancy</button>');
            var $newLinkLi = $('#panelBandVacancies').append(addNewBandVacancy);
            $('#tab-content').append('<br/><button type="submit" class="btn btn-primary"><span class="fa fa-floppy-o"></span> Submit Changes</button>');
            bandVacanciesHolder = $('#panelBandVacancies');
            bandVacanciesHolder.append($newLinkLi);
            bandVacanciesHolder.data('index', bandVacanciesHolder.find(':input').length);

            addNewBandVacancy.on('click', function (e) {
                e.preventDefault();
                addForm(bandVacanciesHolder, 'divShowNewBandVacancy');
            });

            $(document).on("click", 'button[id^="deleteBandVacancyAssociation"]', function (e) {
                $(this).parent().parent().remove();
            });
            $("#ze_babundle_band_submit").hide();
            $("#btnShowNewLocation").appendTo($("#s2id_ze_babundle_{{edit_form.vars.value.className}}_addresses"));
            $("div[id^='ze_babundle_band_documents']").remove();
        });


        $(function () {
            $("#deleteDocument").on("click", function () {
                var ids = Array();
                var checked = $('input[name="chkDocuments"]:checked');
                var count=checked.length;
                $("div[id^='divDocument']").find("input:checked").each(function (i, ob) {
                    ids.push($(ob).attr('id'));
                });

                bootbox.confirm("Are you sure?", function (result) {
                    if (result) {
                        var url = Routing.generate('api_deleteDocumentsAction', {'ids':ids.join(),'associationId':{{edit_form.vars.data.id  }} });
                        var method = 'POST'
                        $.ajax({
                            url: url,
                            type: method
                        }).done(function (data) {
                            debugger;
                            if (typeof data != 'undefined') {
                                for(var i =0;i<count;i++){
                                    $("#divDocument" + ids[i]).remove();
                                }

                            }

                        });



                    }

                });
            });
            $('#frm_upload_document')
                    .submit(function (e) {

                        var action = "{{ path('document_create', { 'aid':  edit_form.vars.data.id })  }}";
                        var method = 'POST'
                        $.ajax({
                            url: action,
                            type: method,
                            data: new FormData(this),
                            processData: false,
                            contentType: false
                        }).done(function (data) {
                            if (typeof data != 'undefined') {
                                var strDiv = '<div class="col-xs-6 col-sm-4 col-md-3 col-lg-3" id="divDocument' + data.id + '"><input type="checkbox" name="chkDocuments" id="' + data.id + '"/>' +
                                        '<img src=" ' + data.path + '"></div>';
                                $("div[id^='divDocument']").last().append(strDiv);

                            }

                        });


                        e.preventDefault();
                    });

            $("#btnShowNewDocument").change(function (e) {
                $('#frm_upload_document').submit();
            });

        });

    </script>
{% endblock %}

src/ZE/BABundle/Resources/views/genres.html.twig
{% block genres_container %}
    {% if entity.genres is defined %}
        <div class="text-left ">Genres:
                {% for genre in entity.genres %}
                    {% set genre_folder = 'img/genres/' ~ genre.slug ~ '.jpg' %}
                    <span class="genre" >{{ genre.name }}
                        <img src="{{  genre_folder | imagine_filter('thumb') }}" />
                    </span>
                {% endfor %}
        </div>
    {% endif %}
{% endblock genres_container%}

src/ZE/BABundle/Resources/views/instruments.html.twig
{% block instruments_container %}
    {% if entity.instruments is defined %}
        <div class="text-left ">Instruments:
                {% for instrument in entity.instruments %}
                    {% set instrument_folder = 'img/instruments/' ~ instrument.slug ~ '.png' %}
                    <span class="instrument">{{ instrument.name }}
                        <img src="{{  instrument_folder | imagine_filter('thumb') }}" />
                    </span>
                {% endfor %}
        </div>
    {% endif %}
{% endblock instruments_container%}

src/ZE/BABundle/Resources/views/item_container.html.twig
{% block item_container %}
    {% if container_div_class  is not defined %} {% set container_div_class = "row multi-columns-row" %} {% endif %}
    {% if content_div_class is not defined %} {% set content_div_class="col-xs-6 col-sm-4 col-md-3 col-lg-3" %}  {% endif %}
    {% if is_edit is not defined %} {% set is_edit = false %}  {% endif %}

    <div class="{{ container_div_class }} ">
        {% for entity in pagination %}
            {% if is_edit == false%}
                {% set entity_show_path= path( entity_type ~'_show', { 'slug': entity.slug }) %}
            {% else %}
                {% set entity_show_path= path( entity_type ~'_edit', { 'id': entity.id}) %}
            {% endif %}
            <div class="{{ content_div_class }}">
                <div class="association-item">
                    <div class="association-image">
                        <a href="{{ entity_show_path }}">
                            {% if entity.documents[0] is defined %}
                                <img src="/{{ entity.documents[0].getWebPath }}" alt="">
                            {% else %}
                                <img src="http://placehold.it/600x360" alt="Project Name">
                            {% endif %}
                        </a>
                    </div>
                    <div class="association-info">
                        <ul>
                            <li class="association-project-name">{{ entity.name }}</li>

                            {% include 'ZEBABundle::genres.html.twig' %}
                            {% include 'ZEBABundle::locations.html.twig' %}
                            <p>{% include 'ZEBABundle::instruments.html.twig' %}</p>
                            <li class="read-more"><a href="{{ entity_show_path }}" class="btn">Read more</a></li>
                        </ul>
                    </div>
                    {% if entity_type == 'band' and is_granted('ROLE_USER') and not app.user.id == entity.user.id%}
                        <br>
                        <div>
                            <button href="{{ path('api_joinBandRequestAction', {'bandId': entity.id} ) }}" type="button"
                                    class="btn btn-primary">Request Audition
                            </button>
                        </div>
                    {% endif %}
                </div>

            </div>

        {% endfor %}

    </div>
    {% block navigaion %}
        <div class="navigation">
            {{ knp_pagination_render(pagination) }}
        </div>
    {% endblock navigaion %}
{% endblock item_container %}

src/ZE/BABundle/Resources/views/locations.html.twig
{% block addresses_container %}
    {% if entity.addresses is defined %}
        <div class="float-left text-left">Locations:
                {% for address in entity.addresses %}
                    {% set flag_path = '/img/flags/' ~ address.city.country.code |lower ~ '.png' %}
                    {% block location_text %}{% endblock location_text %}
                        <a href="{{ path( entity.className , { 'address': address.id} ) }}"><img class="flag" src="{{  flag_path  }}" /></a>
                    {% block location_suffix %}{% endblock location_suffix %}
                {% endfor %}
        </div>
    {% endif %}
{% endblock addresses_container%}

src/ZE/BABundle/Resources/views/musicians_associated.html.twig
{% extends 'ZEBABundle::_associated_group.html.twig' %}
{% block assoc_loop %}
    {% set entity_show_path= path( type ~'_show', { 'slug': assoc.slug }) %}
    {% include 'ZEBABundle::_associated_row.html.twig' with {'assoc' : assoc} %}
{% endblock assoc_loop %}

src/ZE/BABundle/Resources/views/request_audition_button.html.twig
{% block request_audition_button %}
    <p>
    <div>
        <button data-href="{{ path('api_joinBandRequestAction', {'bandId': bandId, 'musicianId':musicianId} ) }}"
                type="button" class="btn btn-primary">Request Audition To Join Band
        </button>
    </div>
    </p>
{% endblock request_audition_button %}

src/ZE/BABundle/Resources/views/show_association.html.twig
{% extends '::base.html.twig' %}

{% block container %}
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h1>{{ entity.name }}</h1>
            {% embed 'ZEBABundle::locations.html.twig' %}
                {% block location_text %}
                    {{ address.city.name  }},
                    {% if address.region.longName is defined %}{{ address.region.longName }},{% endif %}
                    {{ address.city.country.name }}
                {% endblock location_text %}
            {% endembed %}
            <br>
            <p>{% include 'ZEBABundle::genres.html.twig' %}</p>
            <p>{% include 'ZEBABundle::instruments.html.twig' %}</p>
            <p>Description: {{ entity.description }}</p>
            {% if entity.getClassName == 'band' and is_granted('ROLE_USER') and ( userInBand == false)%}
                {% if app.user.musicians|length == 1%}
                    {% include 'ZEBABundle::request_audition_button.html.twig'
                        with {'bandId': entity.id, 'musicianId': app.user.musicians[0].id} %}
                {% elseif app.user.musicians|length > 1%}
                    {% include 'ZEBABundle::request_audition_select_musician.html.twig'
                    with {'bandId': entity.id,'musicians': app.user.musicians} %}
                {% endif %}
            {% endif %}
            {% if entity.bands is defined and entity.bands|length > 0%}
                {% include 'ZEBABundle::bands_associated.html.twig' with {'assocs': entity.bands, 'type' : 'band'} %}
            {% endif %}
            {% if entity.musicians is defined and entity.musicians|length > 0%}
                {% include 'ZEBABundle::musicians_associated.html.twig' with {'assocs': entity.musicians, 'type' : 'musician'} %}
            {% endif %}

        </div>
    </div>
{% endblock %}